"""Markdown report generation utilities"""

from datetime import datetime
from typing import List, Dict, Any, Optional


class MarkdownReport:
    """Generate formatted Markdown reports"""
    
    def __init__(self, title: str):
        self.title = title
        self.sections: List[str] = []
        self.summary_status = "unknown"  # green, yellow, red
        self.findings: List[Dict[str, Any]] = []
        self.recommendations: List[str] = []
        self.checked_items: List[str] = []
    
    def set_summary(self, status: str, summary: str):
        """Set summary with status (green/yellow/red)"""
        self.summary_status = status
        self.sections.append(f"## 📊 Summary\n\n**Status:** {self._status_emoji(status)} {status.upper()}\n\n{summary}\n")
    
    def add_finding(self, severity: str, title: str, description: str, recommendation: Optional[str] = None):
        """Add a finding (info/warning/critical)"""
        self.findings.append({
            'severity': severity,
            'title': title,
            'description': description,
            'recommendation': recommendation
        })
        if recommendation:
            self.recommendations.append(recommendation)
    
    def add_recommendation(self, recommendation: str):
        """Add a recommendation"""
        self.recommendations.append(recommendation)
    
    def add_checked_item(self, item: str):
        """Add an item that was checked"""
        self.checked_items.append(item)
    
    def _status_emoji(self, status: str) -> str:
        """Get emoji for status"""
        emoji_map = {
            'green': '✅',
            'yellow': '⚠️',
            'red': '❌',
            'unknown': '❓'
        }
        return emoji_map.get(status.lower(), '❓')
    
    def _severity_emoji(self, severity: str) -> str:
        """Get emoji for severity"""
        emoji_map = {
            'info': 'ℹ️',
            'warning': '⚠️',
            'critical': '🔴',
            'good': '✅'
        }
        return emoji_map.get(severity.lower(), 'ℹ️')
    
    def generate(self) -> str:
        """Generate the complete Markdown report"""
        lines = [
            f"# {self.title}",
            f"\n**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}\n",
        ]
        
        # Add all sections
        lines.extend(self.sections)
        
        # Findings table
        if self.findings:
            lines.append("## 🔍 Findings\n")
            lines.append("| Severity | Title | Description |")
            lines.append("|----------|-------|-------------|")
            for finding in self.findings:
                severity_emoji = self._severity_emoji(finding['severity'])
                title = finding['title'].replace('|', '\\|')
                desc = finding['description'].replace('|', '\\|')[:100] + "..." if len(finding['description']) > 100 else finding['description']
                desc = desc.replace('\n', ' ')
                lines.append(f"| {severity_emoji} {finding['severity']} | {title} | {desc} |")
            lines.append("")
        
        # Recommendations
        if self.recommendations:
            lines.append("## 💡 Recommendations\n")
            for i, rec in enumerate(self.recommendations, 1):
                lines.append(f"{i}. {rec}")
            lines.append("")
        
        # What was checked
        if self.checked_items:
            lines.append("## ✅ What Was Checked\n")
            for item in self.checked_items:
                lines.append(f"- {item}")
            lines.append("")
        
        # Footer
        lines.append("---\n")
        lines.append(f"*Report generated by AutoBuilder Bot*")
        
        return "\n".join(lines)
    
    def save(self, filepath: str) -> bool:
        """Save report to file"""
        try:
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(self.generate())
            return True
        except Exception as e:
            print(f"Error saving report: {e}")
            return False

